- name: Ensures /etc/ima exists
  file: path=/etc/ima state=directory

- name: Copy ima-policy
  copy:
    src: /root/keylime/demo/ima-policy
    dest: /etc/ima/ima-policy
    mode: 0644
    remote_src: yes