- name: update/upgrade all packages
  dnf:
      name: "*"
      state: latest

- name: install git
  dnf:
      name: git
      state: latest

- name: install automake
  dnf:
      name: automake
      state: latest

- name: install libtool
  dnf:
      name: libtool
      state: latest

- name: install autoconf
  dnf:
      name: autoconf
      state: latest

- name: install autoconf-archive
  dnf:
      name: autoconf-archive
      state: latest

- name: install libstdc++-devel
  dnf:
      name: libstdc++-devel
      state: latest

- name: install gcc
  dnf:
      name: gcc
      state: latest

- name: install pkg-config
  dnf:
      name: pkg-config
      state: latest

- name: install uriparser-devel
  dnf:
      name: uriparser-devel
      state: latest

- name: install libgcrypt-devel
  dnf:
      name: libgcrypt-devel
      state: latest

- name: install dbus-devel
  dnf:
      name: dbus-devel
      state: latest

- name: install glib2-devel
  dnf:
      name: glib2-devel
      state: latest

- name: install compat-openssl10-devel
  dnf:
      name: compat-openssl10-devel
      state: latest

- name: install libcurl-devel
  dnf:
      name: libcurl-devel
      state: latest

- name: install python3-pip
  dnf:
      name: python3-pip
      state: latest

- name: install PyYAML
  dnf:
      name: python3-pyyaml
      state: latest

- name: install python3-m2crypto
  dnf:
      name: python3-m2crypto
      state: latest

- name: install python3-tornado
  dnf:
      name: python3-tornado
      state: latest

- name: install python3-simplejson
  dnf:
      name: python3-simplejson
      state: latest

- name: install python3-requests
  dnf:
      name: python3-requests
      state: latest

- name: Install libselinux-python3
  dnf:
    name: libselinux-python3
    state: latest

- name: install yaml-cpp-devel
  dnf:
      name: yaml-cpp-devel
      state: latest

- name: install procps-ng
  dnf:
      name: procps-ng
      state: latest

- name: install tpm2-tss
  dnf:
      name: tpm2-tss
      state: latest

- name: install tpm2-tools
  dnf:
      name: tpm2-tools
      state: latest

- name: install tpm2-abrmd
  dnf:
      name: tpm2-abrmd
      state: latest
