---
- hosts: all
  become: true
  pre_tasks:
    - name: 'install python3'
      raw: sudo dnf -y install python3
    - name: 'install libselinux-python'
      raw: sudo dnf -y install libselinux-python3
  roles:
    - ansible-keylime
